package main

import (
	"fmt"
	"os"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}

	cmd, args := os.Args[1], os.Args[2:]

	var err error
	switch cmd {
	case "login":
		err = cmdLogin(args)
	case "logout":
		err = cmdLogout(args)
	case "verify-cred":
		err = cmdVerifyCred(args)
	case "-h", "--help", "help":
		usage()
	case "add", "commit", "status", "checkout", "serve", "sqldump":
		if err = requireCLIAuth(); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		switch cmd {
		case "add":
			err = cmdAdd(args)
		case "commit":
			err = cmdCommit(args)
		case "status":
			err = cmdStatus(args)
		case "checkout":
			err = cmdCheckout(args)
		case "serve":
			err = cmdServe(args)
		case "sqldump":
			err = cmdSQLDump(args)
		}
	default:
		fmt.Fprintf(os.Stderr, "unknown command: %s\n\n", cmd)
		usage()
		os.Exit(2)
	}

	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func usage() {
	fmt.Println(`my-git-tool - mini git in Go (powered by go-git)

CLI (most commands require login first — like docker login):
  my-git-tool login -auth-dir DIR [-username U] [-password P] [-session-hours 72]
                                     Verify against *.ini in DIR, store signed CLI session
  my-git-tool logout                 Remove CLI session file

CLI:
  my-git-tool add <path>...          Stage one or more paths
  my-git-tool add -A                 Stage all changes (like git add -A)
  my-git-tool commit -m <message>    Commit staged changes
  my-git-tool status                 Show working tree status
  my-git-tool checkout <branch>      Switch to an existing branch
  my-git-tool checkout -b <branch>   Create and switch to a new branch
  my-git-tool checkout -- <path>...  Discard working-tree changes for paths

Web UI (GitHub Desktop-like):
  my-git-tool serve [-addr :7891] [-repo .] [-auth-dir DIR] [-session-hours 72] [-secure-cookie]
                                     Start the web UI. Optional -auth-dir points to a folder of
                                     *.ini files (one [auth] user per file, from gen_credentials.py);
                                     when set, all /api/* except /api/me and /api/login require a session cookie.

Tools:
  my-git-tool sqldump <file.sqlite>  Dump a SQLite DB as plain SQL text
  my-git-tool verify-cred -file auth.ini -username U -password P
                                     Verify a credentials INI generated by
                                     scripts/gen_credentials.py (HMAC-SHA256
                                     with shared SECRET_KEY)`)
}
